### PR TITLE
Fix FirestoreDataConverter.fromFirestore() being called with QueryDocumentSnapshot from exp

### LINKED ISSUE #4278: DocumentReference from QueryDocumentSnapshot in model converter not typed correctly.
### [REQUIRED] Describe your environment

  * Operating System version: Windows
  * Browser version: Chrome  (87.0.4280.141)
  * Firebase SDK version: 9.1.0
  * Firebase Product: firestore

### [REQUIRED] Describe the problem

When trying to save the DocumentReference from the QueryDocumentSnapshot in the ModelConverter.fromFirestore function. The resulting document reference object is missing several fields.

#### Steps to reproduce:

See code below:

#### Relevant Code:

```
interface MyModel {
  ref: firebase.firestore.DocumentReference;
}

const modelConverter = {
  toFirestore: function (model: MyModel) {
    return _.omit(model, "ref");
  },
  fromFirestore: function (
    snapshot: firebase.firestore.QueryDocumentSnapshot
  ): MyModel {
    const model = snapshot.data();
    // Some kind of validation, etc.
    model.ref = snapshot.ref;
    return model as MyModel;
  },
};

const modelDocumentRef = firebase.firestore()
  .collection("/models")
  .doc("some_id")
  .withConverter(modelConverter);

  modelDocumentRef.onSnapshot((snapshot) => {
  const model = snapshot.data();
  const modelSubcollectionRef = model?.ref.collection("/subcollection");
});
```

Runtime output:

```
Uncaught (in promise) TypeError: model.collection is not a function
```

Instead I have to do:

```
  fromFirestore: function (
    snapshot: firebase.firestore.QueryDocumentSnapshot
  ): MyModel {
    const model = snapshot.data();
    // Some kind of validation, etc.
>   model.ref = firebase.firestore().doc(snapshot.ref.path);
    return model as MyModel;
  },

```

### PR DESCRIPTION
**Pull request by dconeybe**
`FirestoreDataConverter.fromFirestore()` was being invoked with an instance of `QueryDocumentSnapshot` from the experimental SDK; however, it was expected to be invoked with an instance of `QueryDocumentSnapshot` from the Classic SDK. This worked okay, except that the object was lacking attributes like `ref`, which are only provided by the Classic SDK.

The root cause is that the `FirestoreDataConverter` provided by the user was registered directly with the `QueryDocumentSnapshot` from the experimental SDK, and therefore was invoked with types from the experimental SDK. The fix is to instead register a "wrapper" data converter with the `QueryDocumentSnapshot` that calls the underlying data converter with the equivalent objects from the Classic SDK.

There was, however, a side effect of this change that caused `isEqual()` methods (e.g. `DocumentReference.isEqual()`) to incorrectly return `false` if compared with another `DocumentReference` created with the same converter instance. This is because the implementation of `isEqual()` compares the converters using the `===` operator. The wrapper instances that wrapped the same converters were distinct objects, and thus did not compare equal using `===`. The fix was to store each converter in a `WeakMap` mapping it to its wrapper instance so that the same wrapper instance can be used for each given converter, causing `isEqual()` to compare correctly.

Fixes #4278

### CODE REVIEW

File: packages/firestore/src/api/database.ts [hunk 1]
```diff
@@ -552,6 +553,41 @@ export class WriteBatch
   }
 }
 
+class UntypedFirestoreDataConverterAdapter<U>
```
Comment (schmidt-sebastian) [inline packages/firestore/src/api/database.ts:556]: This now looks like the rest of our "Compat" classes. You could follow the existing pattern and start this off as such:

```
class FirestoreDataConverter<U>
  extends Compat<ExpFirestoreDataConverter<U>>
  implements FirestoreDataConverter<T> {
```

I also wonder if thanks to this adapter, we may now be able to stop using the `UntypedFirestoreDataConverterAdapter`.

File: packages/firestore/src/api/database.ts [hunk 2]
```diff
@@ -753,7 +789,7 @@ export class DocumentReference<T = PublicDocumentData>
     return new DocumentReference<U>(
       this.firestore,
       this._delegate.withConverter(
-        converter as UntypedFirestoreDataConverter<U>
+        new UntypedFirestoreDataConverterAdapter(this.firestore, converter)
```
Comment (schmidt-sebastian) [inline packages/firestore/src/api/database.ts:792]: Since we cannot force our users to implement a custom `isEqual` function, the problem you mentioned in chat can likely only be solved by looking at the type of data converter and "unwrapping" the adapter when needed.

This would look something like this:

```
const c1 = this.converter instanceof Compat ? this.converter._delegate : this.converter;
const c2 = that.converter instanceof Compat ? that.converter._delegate : that.converter;

if (c1 == c2) console.log("Woohoo!");
```

FWIW, a more straightforward fix may be to not call https://github.com/firebase/firebase-js-sdk/blob/566a62dd4d54ca6ca8bef8bb4409023050bb9f90/packages/firestore/src/exp/snapshot.ts#L264 when a converter is used, but to instead do something like this:


````
// In the compat class

data() {
  if (!this.converter) return this.delegate.data(); 
  else {
  const snapshot = new ExpQueryDocumentSnapshot(this._firestore, ...,
     new QueryDocumentSnapshot(
        this._firestore,
        this._userDataWriter,
        this._key,
        this._document,
        this.metadata,
        /* converter= */ null
      ));
      return this._converter.fromFirestore(snapshot, options);
  }
}


````

File: packages/firestore/src/api/database.ts (hunk 1 above)
Comment (dconeybe) [reply packages/firestore/src/api/database.ts:556]: Good point about using the `Compat` class.

I was also thinking the same thing about `UntypedFirestoreDataConverterAdapter` not being needed anymore. I think that you're right, if we use this "compat" adapter strategy then we can get rid of `UntypedFirestoreDataConverterAdapter`.

File: packages/firestore/src/api/database.ts (hunk 2 above)
Comment (dconeybe) [reply packages/firestore/src/api/database.ts:792]: I like this more "straightforward" fix. We would just have to be careful to implement `isEqual` to check equality of `this._converter` instead of relying on comparing the `_converter` of the delegate (since it will always be null). I think this is the best approach though so I'm going to try it out.

Comment (schmidt-sebastian) [reply packages/firestore/src/api/database.ts:792]: I believe the `isEqual` problem goes away if we use the "straightforward fix.

Comment (dconeybe) [reply packages/firestore/src/api/database.ts:792]: If we use the "straightforward fix" then the delegate's converter will always be null. Since `refEqual()` checks the converter for equality, that logic would need to be moved into the `isEqual()` methods to maintain the same semantics of `isEqual()`. Otherwise, the converters would not be considered when checking for equality, and the current logic *does* check the converters for equality.

File: packages/firestore/src/api/database.ts [hunk 3]
```diff
@@ -552,6 +553,61 @@ export class WriteBatch
...
+    delegate: PublicFirestoreDataConverter<U>
+  ) {
+    super(delegate);
+  }
+
+  fromFirestore(snapshot: unknown, options?: unknown): U {
+    return this._delegate.fromFirestore(
+      new QueryDocumentSnapshot<U>(
+        this._firestore,
+        snapshot as ExpQueryDocumentSnapshot<U>
```
Comment (schmidt-sebastian) [inline packages/firestore/src/api/database.ts:572]: This unfortunately causes any data (such as DocumentReferences) to be returned as exp-types. You need to follow the pattern here: https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/src/api/database.ts#L417

File: packages/firestore/src/api/database.ts [hunk 4]
```diff
@@ -552,6 +553,61 @@ export class WriteBatch
...
+  private static readonly INSTANCES = new WeakMap();
+
+  private constructor(
+    private readonly _firestore: Firestore,
+    delegate: PublicFirestoreDataConverter<U>
+  ) {
+    super(delegate);
+  }
+
+  fromFirestore(snapshot: unknown, options?: unknown): U {
```
Comment (schmidt-sebastian) [inline packages/firestore/src/api/database.ts:568]: Can you use `ExpQueryDocumentSnapshot` and `PublicSnapshotOptions` here (instead of unknown)?

File: packages/firestore/src/api/database.ts [hunk 5]
```diff
@@ -552,6 +553,61 @@ export class WriteBatch
   }
 }
 
+class UntypedFirestoreDataConverterAdapter<U>
```
Comment (schmidt-sebastian) [inline packages/firestore/src/api/database.ts:556]: Can you add some JSDoc for this class? You can likely summarize your PR description.

File: packages/firestore/test/integration/api/database.test.ts [hunk 6]
```diff
@@ -1373,6 +1373,25 @@ apiDescribe('Database', (persistence: boolean) => {
       }
     };
 
+    class ModelWithRef {
```
Comment (schmidt-sebastian) [inline packages/firestore/test/integration/api/database.test.ts:1376]: Could you re-use the Post-Converter? That might cut down on the extra lines in this file.

File: packages/firestore/test/integration/api/database.test.ts [hunk 7]
```diff
@@ -1373,6 +1373,25 @@ apiDescribe('Database', (persistence: boolean) => {
...
+      constructor(readonly ref: firestore.DocumentReference<ModelWithRef>) {}
+    }
+
+    const modelWithRefConverter = {
+      toFirestore(model: ModelWithRef): firestore.DocumentData {
+        // Remove the "ref" attribute, since it's not meant to be stored in
+        // the Firestore database.
+        const { ['ref']: _, ...rest } = model;
+        return rest;
```
Comment (schmidt-sebastian) [inline packages/firestore/test/integration/api/database.test.ts:1385]: Doesn't this remove all the data since model only contains `ref`?

File: packages/firestore/test/integration/api/database.test.ts [hunk 8]
```diff
@@ -1590,6 +1609,51 @@ apiDescribe('Database', (persistence: boolean) => {
...
+    });
+
+    it('Correct snapshot specified to fromFirestore() when registered with CollectionReference', () => {
+      return withTestDb(persistence, async db => {
+        const untypedCollection = db
+          .collection('/models')
+          .doc()
+          .collection('sub');
+        const collection = untypedCollection.withConverter(
+          modelWithRefConverter
```
Comment (schmidt-sebastian) [inline packages/firestore/test/integration/api/database.test.ts:1630]: I would expect that this converter does an instanceof check.

File: packages/firestore/test/integration/api/database.test.ts [hunk 9]
```diff
@@ -1590,6 +1609,51 @@ apiDescribe('Database', (persistence: boolean) => {
...
       });
     });
+
+    it('Correct snapshot specified to fromFirestore() when registered with DocumentReference', () => {
+      return withTestDb(persistence, async db => {
+        const untypedDocRef = db.collection('/models').doc();
+        const docRef = untypedDocRef.withConverter(modelWithRefConverter);
+        await docRef.set(new ModelWithRef(docRef));
+        const docSnapshot = await docRef.get();
+        expect(untypedDocRef.isEqual(docSnapshot.data()!.ref)).to.be.true;
```
Comment (schmidt-sebastian) [inline packages/firestore/test/integration/api/database.test.ts:1619]: This uses `refsEqual` which compares the path and the converter, but doesn't perform an instanceof check. You should add an instanceof check here and make sure that it fails before your changes.

File: packages/firestore/src/api/database.ts [hunk 10]
```diff
@@ -753,7 +809,10 @@ export class DocumentReference<T = PublicDocumentData>
     return new DocumentReference<U>(
       this.firestore,
       this._delegate.withConverter(
-        converter as UntypedFirestoreDataConverter<U>
+        UntypedFirestoreDataConverterAdapter.getInstance(
+          this.firestore,
+          converter
```
Comment (schmidt-sebastian) [inline packages/firestore/src/api/database.ts:814]: If we store this as an instance member (i.e. rather than storing the original converter we store the `UntypedFirestoreDataConverterAdapter`), do we still need the `getInstance` method and its map? The converter would then be the same across calls. You can even pass the UntypedFirestoreDataConverterAdapter down from the CollectionReference to the DocumentReference if you make sure that you never wrap a converter twice.

File: packages/firestore/src/api/database.ts (hunk 5 above)
Comment (schmidt-sebastian) [inline packages/firestore/src/api/database.ts:556]: Also the obligatory comment on naming: All classes in this file are essentially adapters. I would just use the public API name for this, which follows the usage across this file (e.g. DocumentReference, DocumentSnapshot and the newly introduced FirestoreDataConverter).

**Review by schmidt-sebastian — COMMENTED** [review]
Thank you for this fix! I have a couple of lame suggestions for you, but I am impressed. Especially with the PR description :)

File: packages/firestore/test/integration/api/database.test.ts (hunk 9 above)
Comment (dconeybe) [reply packages/firestore/test/integration/api/database.test.ts]: I changed this to:

```
const ref = docSnapshot.data()!.ref!;
expect(ref).to.be.an.instanceof(firestore.DocumentReference);
expect(untypedDocRef.isEqual(ref)).to.be.true;
```

However, at runtime it fails with that error we were talking about a few days ago:

```
Error: Cannot find module '@firebase/firestore-types'
Require stack:
- packages/firestore/test/integration/api/database.test.ts
...
```

Do you know how I can work around this problem? I'm not sure what the "correct" way is to import `DocumentReference` from `database.ts`.

File: packages/firestore/test/integration/api/database.test.ts (hunk 8 above)
Comment (dconeybe) [reply packages/firestore/test/integration/api/database.test.ts]: I'm not sure what you are suggesting. Can you clarify?

File: packages/firestore/src/api/database.ts (hunk 5 above)
Comment (dconeybe) [reply packages/firestore/src/api/database.ts]: Done.

Comment (dconeybe) [reply packages/firestore/src/api/database.ts]: Done.

File: packages/firestore/src/api/database.ts (hunk 10 above)
Comment (dconeybe) [reply packages/firestore/src/api/database.ts]: I also realized that we need to key the WeakMap on both Firestore in addition to the converter instance, so that the object specified to the wrapper converter will be associated with the correct Firestore instance.

File: packages/firestore/test/integration/api/database.test.ts (hunk 9 above)
Comment (schmidt-sebastian) [reply packages/firestore/test/integration/api/database.test.ts]: Sorry, this is a bit more complicated than I anticipated. You need to get the actual instance of DocumentReference from "firebase_export" rather than the type. "firebase_export" is used so that it can be replaced in the minified test. Here is a patch with the changes: https://gist.github.com/schmidt-sebastian/7201fe874a6f463e0ad2256780386107

Note that you must also edit ../../integration/firestore since this test file is part of the minified integration tests that runs on CI.

File: packages/firestore/test/integration/api/database.test.ts (hunk 8 above)
Comment (dconeybe) [reply packages/firestore/test/integration/api/database.test.ts]: Ahh I see what you mean (from the Gist you posted: https://gist.github.com/schmidt-sebastian/7201fe874a6f463e0ad2256780386107). You were asking for an instanceof check in the fromFirestore() method. I've included this.

File: packages/firestore/test/integration/api/database.test.ts (hunk 9 above)
Comment (dconeybe) [reply packages/firestore/test/integration/api/database.test.ts]: Thanks for the gist! That's perfect. I've incorporated your suggestion.

**Review by schmidt-sebastian — APPROVED** [review]
