### PR TITLE
Fix query string parsing

### LINKED ISSUE #517: [database] FIREBASE WARNING: Invalid query string segment:
https://github.com/firebase/firebase-js-sdk/blob/5038cec639e69562f7b3eb1f0e281cf309c79c28/packages/database/src/core/util/libs/parser.ts#L54

@tonymeng This warning now appears during `firebase.initializeApp(config)` even where `config.databaseURL` does not include any `ns` query parameter.

### PR DESCRIPTION
**Pull request by tonymeng**
Fixes #517

### CODE REVIEW

File: packages/database/src/core/util/libs/parser.ts [hunk 1]
```diff
@@ -47,11 +47,14 @@ function decodeQuery(queryString: string): { [key: string]: string } {
...
   for (const segment of queryString.split('&')) {
+    if (segment.length === 0) {
+      continue;
+    }
     const kv = segment.split('=');
     if (kv.length === 2) {
       results[decodeURIComponent(kv[0])] = decodeURIComponent(kv[1]);
     } else {
-      warn('Invalid query string segment: ' + segment);
+      warn('Invalid query string segment: "' + segment + '" in query string: "' + queryString + '"');
```
Comment (schmidt-sebastian) [inline packages/database/src/core/util/libs/parser.ts]: Suggested: 
```
warn(`Invalid query segment '${segment}' in query '${queryString}'`);
```

**Comment by spencexyz** [comment]
Did you guys deploy this on npm?
