### PR TITLE
Check that window is complete in BrowserConnectivityMonitor

### LINKED ISSUE #1824: @firebase/firestore: Firestore (6.0.4): INTERNAL UNHANDLED ERROR: configureNetworkMonitoring
### Environment:

  * Operating System version: Ubuntu 18.04
  * Browser version: Not relevant
  * Firebase SDK version: v6.0.4
  * Firebase Product: Firestore (database)
  * Expo version: v32.0.6 

### Problem description:

I'm developing a app with React Native and Expo and it has been in development since earlier this year. I started intergrating Firebase Firestore and Auth in my app right away with this package and I even have a production build in Testflight, meaning that Firebase works perfectly. I never had a problem with Firebase before.

Yesterday I changed some configuration in my app, such as the display name, some email templates and I've added a custom email domain to send emails from. I also upgraded some packages of my application, including Firebase. I've upgraded these versions:

- firebase from "v5.11.1" to "v6.0.4".
- react-navigation from "v3.9.1" to "v3.11.0". (Probably not relevant)

After all these changes I was still able to register and login my app, but as of today my Firestore is crashing all the time. I would like to make it clear that my **firebase authentication works fine**. 

This is the error I'm getting, it may be different sometimes but it is always the Firestore:
IMG_2267

#### Steps to reproduce:

I would love to provide the steps needed to reproduce this problem, but this seems like a strange bug to me so I'm really not sure if/how you can reproduce this issue.

#### Relevant Code:

Please let me know what code you would like to see. I'm not sure what to post because my application always worked and I **did not change any code**.

#### More information:

You can find a post about this on Reddit which I have made [here](https://www.reddit.com/r/reactnative/comments/bt8ghd/firebasefirestore_not_working_anymore/).

### PR DESCRIPTION
**Pull request by thebrianchen**
Fixes #1824.

### CODE REVIEW

File: packages/firestore/src/platform_browser/browser_connectivity_monitor.ts [hunk 1]
```diff
@@ -64,4 +64,15 @@ export class BrowserConnectivityMonitor implements ConnectivityMonitor {
       callback(NetworkStatus.UNAVAILABLE);
     }
   }
+
+  // TODO(chenbrian): Consider passing in window either into this component or
+  // here for possible tests.
+  /** Checks that all used attributes of window are available. */
+  static isAvailable(): boolean {
+    return (
+      window !== undefined &&
```
Comment (schmidt-sebastian) [inline packages/firestore/src/platform_browser/browser_connectivity_monitor.ts]: You need to use the `typeof window` check.

File: packages/firestore/src/platform_browser/browser_connectivity_monitor.ts [hunk 2]
```diff
@@ -64,4 +64,15 @@ export class BrowserConnectivityMonitor implements ConnectivityMonitor {
       callback(NetworkStatus.UNAVAILABLE);
     }
   }
+
+  // TODO(chenbrian): Consider passing in window either into this component or
+  // here for possible tests.
```
Comment (schmidt-sebastian) [inline packages/firestore/src/platform_browser/browser_connectivity_monitor.ts]: maybe: `for testing via FakeWindow`.
