### PR TITLE
Make the `FunctionsError` class publicly exported

### LINKED ISSUE #8511: FunctionsError exported as a type only, but implementation exists
### Operating System

macOS

### Environment (if applicable)

vite@5

### Firebase SDK Version

"firebase": "10.13.1", "@firebase/functions": "0.11.7"

### Firebase SDK Product(s)

Functions

### Project Tooling

vite@5

### Detailed Problem Description

In my setup FunctionsError is resolved from ./node_modules/@firebase/functions/dist/functions-public.d.ts
image

And it's not a class although an implementation exist in the bundle ./node_modules/firebase/firebase-functions.js

Vite output:
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/firebase_functions.js?v=bd8c5d40' does not provide an export named 'FunctionsError' (at callable.ts:3:3)

Could you pls export FunctionsError as class for better error handling?

### Steps and code to reproduce issue

import { FirebaseError } from 'firebase/app';
import {
  FunctionsError,
} from 'firebase/functions';

console.log({ FunctionsError });

### PR DESCRIPTION
**Pull request by dlarocque**
We should export the `FunctionsError` class to users, so that they can perform instanceof checks.

Tested using:
```js
import { FirebaseError, initializeApp } from "firebase/app";
import { FunctionsError, getFunctions, httpsCallable } from "firebase/functions";

const firebaseConfig = {
  /* ... */
};

const app = initializeApp(firebaseConfig);
const functions = getFunctions(app);
(async () => {
  try {
    const addMessage = httpsCallable(functions, 'addMessage'); // Function does not exist
    await addMessage({ text: 'hello' });
  } catch (err) {
    console.log(err instanceof FirebaseError); // true
    console.log(err instanceof FunctionsError); // true
    throw err;
  }
})();

```

Also added an `expect(error).to.be.instanceOf(FunctionsError)` to all error checks in the tests.

Fixes #8511

### CODE REVIEW

File: packages/functions/src/error.ts [hunk 1]
```diff
@@ -51,6 +51,10 @@ const errorCodeMap: { [name: string]: FunctionsErrorCode } = {
 /**
  * An explicit error that can be thrown from a handler to send an error to the
```
Comment (hsubox76) [inline packages/functions/src/error.ts:52]: Can we put the old interface doc text here? I think it's less confusing for public consumption. It was "An error returned by the Firebase Functions client SDK." The link to the FunctionsErrorCode part is fine, that's good to add, it's just the old text on the class comment seems more internal-facing.

**Review by hsubox76 — APPROVED** [review]

File: docs-devsite/functions.functionserror.md [hunk 2]
```diff
@@ -9,33 +9,50 @@ overwritten. Changes should be made in the source code at
...
 
-## Properties
+## Constructors
 
-|  Property | Type | Description |
+|  Constructor | Modifiers | Description |
 |  --- | --- | --- |
-|  [code](./functions.functionserror.md#functionserrorcode) | [FunctionsErrorCode](./functions.md#functionserrorcode) | A standard error code that will be returned to the client. This also determines the HTTP status code of the response, as defined in code.proto. |
-|  [details](./functions.functionserror.md#functionserrordetails) | unknown | Extra data to be converted to JSON and included in the error response. |
+|  [(constructor)(code, message, details)](./functions.functionserror.md#functionserrorconstructor) |  | Constructs a new instance of the <code>FunctionsError</code> class |
```
Comment (egilmorez) [inline docs-devsite/functions.functionserror.md:28]: I think we want a period here.

File: docs-devsite/functions.functionserror.md [hunk 3]
```diff
@@ -9,33 +9,50 @@ overwritten. Changes should be made in the source code at
...
+## Properties
 
-## FunctionsError.code
+|  Property | Modifiers | Type | Description |
+|  --- | --- | --- | --- |
+|  [details](./functions.functionserror.md#functionserrordetails) |  | unknown | Extra data to be converted to JSON and included in the error response. |
 
-A standard error code that will be returned to the client. This also determines the HTTP status code of the response, as defined in code.proto.
+## FunctionsError.(constructor)
+
```
Comment (egilmorez) [inline docs-devsite/functions.functionserror.md:37]: Period here too.

**Review by egilmorez — APPROVED** [review]
LG with tiny nits, thanks!
