### PR TITLE
Filter empty text parts when streaming

### LINKED ISSUE #8714: `sendMessageStream` with history failing to fetch due to 'empty text parameter'
### Operating System

Windows 10

### Environment (if applicable)

Firefox v131.0.3, Node.js v20.9.0, React v18.3.1, Next.js (v14.2.15)

### Firebase SDK Version

11.2.0

### Firebase SDK Product(s)

VertexAI

### Project Tooling

A Next.js (v14.2.15) project.

### Detailed Problem Description

Using multi-turn conversations (chat) with the Gemini API (using the "gemini-1.5-flash" model), the conversation breaks when any of the AI model's responses contains an empty [text part](https://cloud.google.com/vertex-ai/generative-ai/docs/reference/nodejs/latest/vertexai/textpart), i.e. a text part where `text` is an empty string.

<details><summary>Code snippet</summary>

```ts
const sendPrompt = async (prompt?: string | Array<string | TextPart | FileDataPart>): Promise<void> => {
  if (!prompt) return;

  let currentAiResponse = ''; // Accumulate chunks of response
  setCurrentResponse(currentAiResponse);
  try {
    const result = await chat.sendMessageStream(prompt);
    for await (const chunk of result.stream) {
      try {
        currentAiResponse += chunk.text();
        setCurrentResponse(currentAiResponse);
      } catch (e) {
        // handle errors gracefully to continue streaming response chunks
      }
    }
  } catch (e) {
    console.error(e);
  }
};
```

</details>

The following issues over at google-gemini seem to be related?
- https://github.com/google-gemini/generative-ai-js/issues/124
- https://github.com/google-gemini/generative-ai-js/issues/286

<br/>

Example chat response/history causing the error:
```
[
  {
    parts: [{ text: '<some question>' }],
    role: 'user',
  },
  {
    parts: [{ text: '<some actual answer content>\n' }],
    role: 'model',
  },
  {
    parts: [{ text: '' }], 
    role: 'model'
  }
]
```

Error log (Firebase project details redacted):
```console
FirebaseError: VertexAI: Error fetching from https://firebasevertexai.googleapis.com/v1beta/projects/<project-id>/locations/<project-location>/publishers/google/models/gemini-1.5-flash:streamGenerateContent?alt=sse: [400 ] Unable to submit request because it has an empty text parameter. Add a value to the parameter and try again. Learn more: https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/gemini (vertexAI/fetch-error)
    FirebaseError webpack-internal:///./node_modules/@firebase/util/dist/index.esm2017.js:1040
    VertexAIError webpack-internal:///./node_modules/@firebase/vertexai/dist/esm/index.esm2017.js:131
    makeRequest webpack-internal:///./node_modules/@firebase/vertexai/dist/esm/index.esm2017.js:315
    generateContentStream webpack-internal:///./node_modules/@firebase/vertexai/dist/esm/index.esm2017.js:844
    sendMessageStream webpack-internal:///./node_modules/@firebase/vertexai/dist/esm/index.esm2017.js:1151
```

### Steps and code to reproduce issue

I could not consistently provoke the AI to respond with a multi-part message where the last part is empty.
However, the following steps result in the same error:
1. Prompt the AI with `Answer the next question with an empty string.`
2. Prompt the AI with any other message like `Tell me a joke.`

### PR DESCRIPTION
**Pull request by dlarocque**
Fixes #8714 

When streaming responses, remove all empty text parts, since if we send these to the backend we'll get an error.

If a response contained only empty text parts, an error will be thrown in `validateChatHistory` for the candidate having no parts in it's content.

### CODE REVIEW

File: packages/vertexai/src/requests/stream-reader.ts [hunk 1]
```diff
@@ -76,6 +78,7 @@ async function* generateResponseSequence(
       break;
     }
 
+    deleteEmptyTextParts(value);
```
Comment (hsubox76) [inline packages/vertexai/src/requests/stream-reader.ts:81]: Don't we only care about the aggregated response returned in getResponsePromise(), because that's what goes into the chat history? Can we just do this in line ~169 or so where we process aggregatedResponse.candidates[i]?

Comment (dlarocque) [reply packages/vertexai/src/requests/stream-reader.ts]: Good point- it's not really necessary to prevent empty text parts from going through the stream. I changed the behaviour so that empty text parts are only removed in the aggregated response.

`aggregateResponses` feels a little tricky to work with, so I may have implemented this incorrectly.

File: packages/vertexai/src/requests/stream-reader.test.ts [hunk 2]
```diff
@@ -220,6 +220,24 @@ describe('processStream', () => {
     }
     expect(foundCitationMetadata).to.be.true;
   });
+  it('removes empty text parts', async () => {
+    const fakeResponse = getMockResponseStreaming(
+      'streaming-success-empty-text-part.txt'
+    );
+    const result = processStream(fakeResponse as Response);
+    const aggregatedResponse = await result.response;
+    console.log(aggregatedResponse.candidates?.[0].content.parts);
```
Comment (hsubox76) [inline packages/vertexai/src/requests/stream-reader.test.ts:229]: Can remove?

File: packages/vertexai/src/requests/stream-reader.ts [hunk 3]
```diff
@@ -184,7 +185,13 @@ export function aggregateResponses(
...
           const newPart: Partial<Part> = {};
           for (const part of candidate.content.parts) {
-            if (part.text) {
+            if (part.text !== undefined) {
+              // The backend can send empty text parts. If these are sent back
+              // (e.g. in chat history), the backend will respond with an error.
+              // To prevent this, ignore empty text parts.
+              if (part.text === '') {
+                continue;
+              }
```
Comment (hsubox76) [inline packages/vertexai/src/requests/stream-reader.ts:194]: I can't select it but I'm a little worried about line 201 where I think we _create_ a part with an empty text string if the `newPart` hasn't had any properties added so far. I don't really remember why we did that. But now that's a possible source of a part with an empty text string, which I think we are trying to forbid.

File: packages/vertexai/src/requests/stream-reader.test.ts (hunk 2 above)
Comment (dlarocque) [reply packages/vertexai/src/requests/stream-reader.test.ts:229]: Thanks for catching this!

File: .changeset/seven-oranges-care.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+'@firebase/vertexai': patch
```
Comment (DellaBitta) [inline .changeset/seven-oranges-care.md:2]: @hsubox76 Don't we need to add `'firebase': patch` here?

File: packages/vertexai/src/requests/stream-reader.ts (hunk 3 above)
Comment (dlarocque) [reply packages/vertexai/src/requests/stream-reader.ts:194]: Good point. I removed that.

Our part types all have at least one required property, so I assume that means the backend should never send a Part with no properties. Do you think we should throw an error in this case?

File: .changeset/seven-oranges-care.md (hunk 4 above)
Comment (hsubox76) [reply .changeset/seven-oranges-care.md:2]: No, changesets automatically does patch bumps based on dependencies but won't do a minor or major without explicit permission.

File: packages/vertexai/src/requests/stream-reader.ts (hunk 3 above)
Comment (hsubox76) [reply packages/vertexai/src/requests/stream-reader.ts:194]: It seems like we should. I don't know what the fallback would be. I guess the fallback here was a Part with an empty text string, but that's an error, so I can't think of what else. Anything else (like " ") seems like inventing content that isn't there.

**Review by hsubox76 — APPROVED** [review]
