### PR TITLE
Surface all App Check errors in public getToken() method

### LINKED ISSUE #8822: app-check: getToken with forceRefresh:true swallows errors and returns cached token
### Operating System

macOS Sonoma 14.5

### Environment (if applicable)

Chrome

### Firebase SDK Version

10.14.1

### Firebase SDK Product(s)

AppCheck

### Project Tooling

React app with Webpack and jest

#### What I was trying to achieve
I expected `getToken(appCheckInstance, { forceRefresh: true })` to return a fresh App Check token or throw an error if the request failed (e.g., due to network issues or misconfiguration). This would allow proper error handling in my application.

#### What actually happened
When an error occurs, `getToken` does not return or throw it. Instead, it silently returns the cached token (if a valid one exists), making failures undetectable programmatically.

#### Unexpected behavior
- Errors are logged internally in the console but **not surfaced** to the caller.
- This prevents proper error handling, as failures cannot be detected in code.
-  This causes the third-party caller to receive the cached token without realizing that it is not the fresh token they requested, but instead the cached one.

#### Code Reference:
In the `getToken` function, when an error occurs and `forceRefresh` is `true`, if a valid cached token exists, the error is assigned to the `internalError` property of the token result object. However, this `internalError` is never surfaced to the caller, and the function silently returns the cached token instead of propagating the error. This appears to be an oversight in handling the `forceRefresh` case, specifically in error scenarios: https://github.com/firebase/firebase-js-sdk/blob/42cea4810bb6d845d4330589381bcd91ea95aee3/packages/app-check/src/internal-api.ts#L187

##### No Network Scenario:
```
[2025-02-26T00:26:51.162Z]  @firebase/app-check: FirebaseError: AppCheck: ReCAPTCHA error. (appCheck/recaptcha-error).
```
Despite this logged error, getToken still returns the last cached token instead of failing.

##### **Invalid ReCAPTCHA Site Key Scenario**
When testing an incorrect ReCAPTCHA site key, the following message appeared in the console:
```
@firebase/app-check: AppCheck: Requests throttled due to 403 error. Attempts allowed again after 01d:00m:00s (appCheck/throttled).
```
Again, the error is logged internally but **not returned to the caller**, preventing proper handling of any errors.

#### **Expected behavior**
Errors should be returned or thrown instead of being logged silently. If throwing the error is not the preferred approach, I would suggest returning the error alongside the token to the third-party caller. This would provide the app with the necessary information to properly detect and handle the failure, ensuring that it is not silently overlooked.

### Steps and code to reproduce issue

1. Initialize Firebase App Check.
2. Call getToken(appCheckInstance, { forceRefresh: true }).
3. Simulate any error getting token such as network issue or invalid App Check configuration.
4. Observe that the function still returns a cached token instead of throwing an error.

### PR DESCRIPTION
**Pull request by hsubox76**
The two main changes here are

- throw "internalError" (background: https://github.com/firebase/firebase-js-sdk/pull/6617) in the public-facing `getToken()` method. Errors here should not block 2P calls to App Check (internal calls from Auth, Firestore, etc)
- Distinguish between an initial network error that causes throttling, and an error thrown by attempting to make a call while a throttle is in effect

I've also decided to stop logging getToken errors with `console.error` - these should all be thrown by the public `getToken()` now, and the internal products calling getToken internally (Auth, Firestore, etc.) have access to the error message in a property of AppCheckTokenResult which they can log in the format they choose.

Fixes #8822

### CODE REVIEW

File: packages/app-check/src/errors.ts [hunk 1]
```diff
@@ -54,7 +55,8 @@ const ERRORS: ErrorMap<AppCheckError> = {
   [AppCheckError.STORAGE_WRITE]:
     'Error thrown when writing to storage. Original error: {$originalErrorMessage}.',
   [AppCheckError.RECAPTCHA_ERROR]: 'ReCAPTCHA error.',
-  [AppCheckError.THROTTLED]: `Requests throttled due to {$httpStatus} error. Attempts allowed again after {$time}`
+  [AppCheckError.INITIAL_THROTTLE]: `{$httpStatus} error. Attempts allowed again after {$time}`,
+  [AppCheckError.THROTTLED]: `Requests throttled due to previous {$httpStatus} error. Attempts allowed again after {$time}`
```
Comment (DellaBitta) [inline packages/app-check/src/errors.ts:59]: nit, these should be transposed to match the order in `ErrorParams` and `AppCheckError`.

**Review by DellaBitta — APPROVED** [review]

File: packages/app-check/src/errors.ts (hunk 1 above)
Comment (hsubox76) [reply packages/app-check/src/errors.ts:59]: Flipped it around the other way on the other two since logically I guess the "initial throttle" should come first.

**Comment by nermeen-mattar** [comment]
@hsubox76 Thank you for addressing this promptly. May I ask when we can expect this fix to be released?
