### PR TITLE
Emulator Idempotency: Auth

### LINKED ISSUE #6824: two attempts to connect to auth emulator cause config error
### [REQUIRED] Environment info

**firebase-tools:** 11.14.3
**Platform:** Windows 11

### [REQUIRED] Test case

This [repo](https://github.com/joaomelo/hot-vue/tree/fbe11b3f0dd23eed26d410127d7cad3fa0b4db90) commit.

### [REQUIRED] Steps to reproduce

Clone the repo, install the project dependencies with `npm i` and firebase tools globally, open the windows terminal, and start emulators with `firebase emulators:exec --project demo-test "vitest run"`

### [REQUIRED] Expected behavior

All test cases are able to connect to firebase emulators.

### [REQUIRED] Actual behavior

After a test case connect to the emulators, the following ones will throw an error of config failed. See image:

error

But if we changed the connection code from this...

```js
function connectToFirebase(connection) {
  const { useEmulators, ...config } = connection;

  const app = initializeApp(config);
  const auth = getAuth(app);
  const db = getFirestore(app);

  if (useEmulators) {
    connectAuthEmulator(auth, "http://localhost:9099", {
      disableWarnings: true,
    });
    connectFirestoreEmulator(db, "localhost", 8080);
  }

  const firebase = { app, auth, db };
  return firebase;
}
```

to this...

```js
function connectToFirebase(connection) {
  const { useEmulators, ...config } = connection;

  const app = initializeApp(config);
  const auth = getAuth(app);
  const db = getFirestore(app);

  if (useEmulators && !auth.config.emulator) {
    connectAuthEmulator(auth, "http://localhost:9099", {
      disableWarnings: true,
    });
    connectFirestoreEmulator(db, "localhost", 8080);
  }

  const firebase = { app, auth, db };
  return firebase;
}
```

all connections go through all right.

pass

I'm claiming this is a bug since there is no documented spec that claims a second connection attempt would fail and that the hack adopted here (`!auth.config.emulator`) uses an undocumented property that could change anytime. The consequence would be a fragile code that can be easily broken in a future path or minor release.

Thanks.
JM

### PR DESCRIPTION
**Pull request by DellaBitta**
### Discussion

Update the `connectAuthEmulator` function to support its invocation more than once. If the Auth instance is already in use, and `connectAuthEmulator` is invoked with the same configuration, then the invocation will now succeed instead of assert.

This unlocks support for web frameworks which may render the page numerous times with the same instances of auth. Before this PR customers needed to add extra code to guard against calling `connectAuthEmulator` in their SSR logic. Now we do that guarding logic on their behalf which should simplify our customer's apps.

Fixes #6824.

### Testing

CI, new tests added to `packages/auth/src/core/auth/emulator.test.ts`.

### API Changes

N/A

### CODE REVIEW

**Review by NhienLam — APPROVED** [review]

File: packages/auth/src/core/auth/emulator.ts [hunk 1]
```diff
@@ -66,15 +61,28 @@ export function connectAuthEmulator(
...
-  authInternal.emulatorConfig = Object.freeze({
+  const emulator = { url: `${protocol}//${host}${portStr}/` };
+  const emulatorConfig = Object.freeze({
     host,
     port,
     protocol: protocol.replace(':', ''),
     options: Object.freeze({ disableWarnings })
   });
 
+  if (!authInternal._canInitEmulator) {
```
Comment (hsubox76) [inline packages/auth/src/core/auth/emulator.ts:72]: I think this technically works but it doesn't make the logic clear. There's two reasons to throw here, one is if they're calling this for the first time too late (after a network call has been made, that's the purpose of `authInternal._canInitEmulator`), and the second reason is if they're calling it for a second time with different args. This makes it look like we're only targeting the second case. It will actually work on the first case, of course, because the local vars `emulator` and `emulatorConfig` will have some properties, and won't match `{}`, but I guess the fact it's nested inside a `deepEqual` doesn't make it clear that's a case we're trying to block on.

I know it's more verbose, but instead of the `|| {}` maybe a separate `_assert` before this one that just tests for the existence of `authInternal.config.emulator` and `authInternal.emulatorConfig` would make it clearer that we're covering 2 different cases?

**Review by hsubox76 — APPROVED** [review]
