### PR TITLE
Overwrite undefined candidate index

### LINKED ISSUE #8566: Vertex AI - `generateContentStream` aggregated output undefined
### Operating System

macOS Sonoma 14.1

### Environment (if applicable)

NodeJS

### Firebase SDK Version

main

### Firebase SDK Product(s)

VertexAI

### Project Tooling

N/A - @dlarocque may have more details

### Detailed Problem Description

Vertex AI omits default values (`index == 0`) when serializing its responses as JSON but the SDK assumes the `index` value will always be there in [`aggregateResponses()`](https://github.com/firebase/firebase-js-sdk/blob/64db19264bb5811683b3413b5c5f1e6b79e5b090/packages/vertexai/src/requests/stream-reader.ts#L149). See https://github.com/FirebaseExtended/vertexai-sdk-test-data/pull/21 for more details ([test failure](https://github.com/FirebaseExtended/vertexai-sdk-test-data/actions/runs/11299334600/job/31430076375?pr=21)).

### Steps and code to reproduce issue

The following snippet demonstrates the issue:
```
async function run() {
  const prompt = "Write a story about a magic backpack."

  const result = await model.generateContentStream(prompt);
  for await (const chunk of result.stream) {
    const chunkText = chunk.text();

    // No issues - WAI
    console.log(chunkText);
  }

  // Not working because of the undefined index
  console.log('aggregated response: ', await result.response);
}

run()
```

### PR DESCRIPTION
**Pull request by dlarocque**
Fixes #8566 

The backend omits the `index` for the first candidate, since 0 is a default value, and protos omit defaults. This causes tests to fail against the v4 mock responses, and aggregated responses will be malformed, since instead of `response.candidate[0] = ...` it ends up being `response.candidate[undefined] = ...`.

### CODE REVIEW

File: packages/vertexai/src/requests/response-helpers.ts [hunk 1]
```diff
@@ -25,6 +25,26 @@ import {
...
+ */
+export function createEnhancedContentResponse(
+  response: GenerateContentResponse
+): EnhancedGenerateContentResponse {
+  /**
+   * The Vertex AI backend omits default values.
+   * This causes the `index` property to be omitted from the first candidate in the
+   * response, since it has index 0, and 0 is a default value.
+   */
+  if (response.candidates && !response.candidates[0].index) {
```
Comment (hsubox76) [inline packages/vertexai/src/requests/response-helpers.ts:40]: This will always kick in if response.candidates exists because if response.candidates[0].index === 0 then that's also falsy and fulfills the second condition. Which is fine I guess if somewhat redundant. Maybe just `if (response.candidates?.[0])` for the same effect. Or if you want to be super precise, make the second condition `response.candidates[0].index === undefined` or `!response.candidates[0].hasOwnProperty('index')`

File: packages/vertexai/src/methods/generate-content.ts [hunk 2]
```diff
@@ -59,7 +59,7 @@ export async function generateContent(
     requestOptions
   );
   const responseJson: GenerateContentResponse = await response.json();
-  const enhancedResponse = addHelpers(responseJson);
+  const enhancedResponse = createEnhancedContentResponse(responseJson);
```
Comment (hsubox76) [inline packages/vertexai/src/methods/generate-content.ts:62]: Did you assign it to a named variable first here and in the other places to increase readability? That's fine with me, seems reasonable, just wondering.

**Review by hsubox76 — APPROVED** [review]
Looks good, two comments, a nit and a question.

File: packages/vertexai/src/methods/generate-content.ts (hunk 2 above)
Comment (dlarocque) [reply packages/vertexai/src/methods/generate-content.ts:62]: I think it improves readability only slightly, but the main reason I like this style because it makes it easier to debug since I can step over and see the return value before returning to the calling function, and I can log the value before it's returned without having to move stuff around.

File: packages/vertexai/src/requests/response-helpers.ts (hunk 1 above)
Comment (dlarocque) [reply packages/vertexai/src/requests/response-helpers.ts]: Thanks for catching this! Fixed
