### PR TITLE
Use userAgent instead of depricated appVersion to check for safari indexDB bug.

### LINKED ISSUE #6509: enablePersistance in an iOS WebView causes queries to take minutes to resolve.
### [REQUIRED] Describe your environment

  * Operating System version: iOS (All)
  * Browser version: Safari 15.5 (Web View ONLY, eg: cordova)
  * Firebase SDK version: 8.10.1
  * Firebase Product: firestore

### [REQUIRED] Describe the problem

After calling enablePersistence, the next query will not resolve for up to 10 minutes. After it resolves, everything seems to work as normal.

~~This looks like a regression of: https://github.com/firebase/firebase-js-sdk/issues/3120~~ More likely to be just un unreleased fix, see first comment.

If enablePersistence is not called, everything works as expected.

#### Steps to reproduce:

1. Call `firestore.enablePersistance();`
2. Do a `.get()`

#### Relevant Code:

N/A

### PR DESCRIPTION
**Pull request by KoryNunn**
Currently firestore persistance is broken in cordova, as WKWebView's appVersion does not match Version/1[45], and appVersion is a depricated feature. This PR swaps to checking the userAgent, which is something cordova apps can affect, allowing some level of mitigation of this issue.

Fixes #6509

### CODE REVIEW

**Comment by KoryNunn** [comment]
@dconeybe I have done the CLA, is there a way to re-run these jobs?

**Comment by dconeybe** [comment]
> @dconeybe I have done the CLA, is there a way to re-run these jobs?

I'm not sure. Tagging @cherylEnkidu and @wu-hui, who were working with you on the related bug https://github.com/firebase/firebase-js-sdk/issues/6739

**Comment by dconeybe** [comment]
Hi @KoryNunn. I think you may have linked to the wrong issue number in the description of this PR. You linked to https://github.com/firebase/firebase-js-sdk/issues/6739, which is why I tagged my team mates, but that issue doesn't appear to be related to appVersion or user agent at all. I think you meant to link to https://github.com/firebase/firebase-js-sdk/issues/6509. Is my thinking correct?

**Comment by dconeybe** [comment]
Please merge in HEAD of the master branch and push it up. The GitHub actions have likely changed quite a bit.

**Comment by KoryNunn** [comment]
> 

I did mean https://github.com/firebase/firebase-js-sdk/issues/6509 sorry.

I'll merge head shortly

**Comment by dconeybe** [comment]
Thanks for updating your PR. Since this dark corner of the Firebase code base is unfamiliar with me, I've reached out to some colleagues for advice.

What do you think about leaving the original "if" condition in place, but adding an "or" clause? Basically, check appVersion _and_ userAgent and applying the workaround if at least one of the conditions is true? That would more likely preserve backwards compatibility IMO.

File: packages/firestore/src/local/indexeddb_persistence.ts [hunk 1]
```diff
@@ -977,7 +977,7 @@ export class IndexedDbPersistence implements Persistence {
         // to make sure it gets a chance to run.
         this.markClientZombied();
 
-        if (isSafari() && navigator.appVersion.match(/Version\/1[45]/)) {
+        if (isSafari() && navigator.userAgent.match(/Version\/1[45]/)) {
```
Comment (dconeybe) [inline packages/firestore/src/local/indexeddb_persistence.ts:980]: Let's do an "or" to check both the appVersion and userAgent.

i.e.

```ts
if (isSafari() && (navigator.appVersion.match(/Version\/1[45]/) || navigator.userAgent.match(/Version\/1[45]/)))
```

**Review by dconeybe — CHANGES_REQUESTED** [review]
Please add a changeset using `yarn changeset`. It should be a patch release of `@firebase/firestore` and `firebase`.

For the changeset description, use something like this:

> Check `navigator.userAgent`, in addition to `navigator.appVersion`, when determining whether to work around an IndexedDb bug in Safari. Notably, this may be helpful for Cordova apps that lack `appVersion` in their webview yet need to apply the workaround.

File: packages/firestore/src/local/indexeddb_persistence.ts (hunk 1 above)
Comment (dconeybe) [reply packages/firestore/src/local/indexeddb_persistence.ts:980]: @KoryNunn If you make this small change to the PR I'd be happy to merge it.

**Comment by KoryNunn** [comment]
I've updated this PR to more robustly work in both Safari and in WKWebView (the web view used in native apps).

In Safari, the match is Version/{number}, in WKWebView, the match is Mobile/{number}.

Also, this bug is present in version 16, so I added that to the check.

File: .changeset/chilled-buckets-sneeze.md [hunk 2]
```diff
@@ -0,0 +1,6 @@
+---
+'@firebase/firestore': patch
+'firebase': patch
+---
+
+Check navigator.userAgent, in addition to navigator.appVersion, when determining whether to work around an IndexedDb bug in Safari. Add check for Mobile/# in addition to Version/# to include WKWebView safari versions in this check.
```
Comment (dconeybe) [inline .changeset/chilled-buckets-sneeze.md:6]: Please remove the 2nd sentence from the changeset. The first sentence is the right amount of information for the release notes. If they want more information they can click on the link from the release notes and see your full change.

File: packages/firestore/src/local/indexeddb_persistence.ts [hunk 3]
```diff
@@ -977,8 +977,8 @@ export class IndexedDbPersistence implements Persistence {
         // to make sure it gets a chance to run.
         this.markClientZombied();
 
-        if (isSafari() && navigator.appVersion.match(/Version\/1[45]/)) {
-          // On Safari 14 and 15, we do not run any cleanup actions as it might
+        if (isSafari() && (navigator.appVersion.match(/(?:Version|Mobile)\/1[456]/) || navigator.userAgent.match(/(?:Version|Mobile)\/1[456]/))) {
```
Comment (dconeybe) [inline packages/firestore/src/local/indexeddb_persistence.ts:980]: Please factor out the regular expression into a local variable, to avoid duplicating it.

e.g. `const versionRegex = /(?:Version|Mobile)\/1[456]/;`

Comment (dconeybe) [inline packages/firestore/src/local/indexeddb_persistence.ts:980]: Please run `yarn prettier` in the `packages/firestore` directory to format the code. It will do something wonky to try to get line wrapping at 80 characters.

**Review by dconeybe — CHANGES_REQUESTED** [review]

**Review by dconeybe — COMMENTED** [review]
LGTM! Will give approval once GitHub Actions pass. Thanks for your time (and a great deal of patience) in making this contribution to the SDK!

**Review by dconeybe — APPROVED** [review]
Please merge at your convenience.

**Comment by KoryNunn** [comment]
"Only those with to this repository can merge pull requests."
