### PR TITLE
Fix isSafari() throwing on React Native (fixes #7962)

### LINKED ISSUE #7962: Firestore crashes after `10.7.1` -> `10.7.2` update in Expo/React Native
### Operating System

iOS 17.2

### Browser Version

React Native 0.73.2 / Hermes

### Firebase SDK Version

10.7.2

### Firebase SDK Product:

Firestore

### Describe your project's tooling

React Native app initialized with Expo

### Describe the problem

After upgrading to Firestore SDK 10.7.2, fetching documents from Firestore causes an error.

The crash occurs during the `isSafari()` call introduced in this commit: https://github.com/firebase/firebase-js-sdk/commit/d7ace80d44ec870c3117cfed04ae6a1988c03c8e#diff-d73aa623e0442e31903665f2d555bbf0e1a317db2009f526e8f7209ebf662917R66 

This is because the `isSafari()` function from `@firestore/utils` accesses `navigator.userAgent`. On React Native, `navigator.userAgent` is `undefined`.

### Steps and code to reproduce issue

```
@firebase/firestore: Firestore (10.7.2): INTERNAL UNHANDLED ERROR:  TypeError: Cannot read property 'includes' of undefined
    at isSafari
    at __PRIVATE_getDefaultRelativeIndexReadCostPerDocument
    at __PRIVATE_QueryEngine
    at createLocalStore
```

### PR DESCRIPTION
**Pull request by Yonom**
In https://github.com/firebase/firebase-js-sdk/pull/7929 some logic was added to Firestore to check for the browser being Safari. This new check for `isSafari()` unexpectedly threw an exception in React Native. This PR fixes the exception by explicitly checking for an object not being `undefined` before using it.

Fixes https://github.com/firebase/firebase-js-sdk/issues/7962

### CODE REVIEW

File: packages/util/src/environment.ts [hunk 1]
```diff
@@ -138,6 +138,7 @@ export function isNodeSdk(): boolean {
 export function isSafari(): boolean {
   return (
     !isNode() &&
+    navigator.userAgent !== undefined && // not react-native
```
Comment (dconeybe) [inline packages/util/src/environment.ts:141]: Please just remove this comment and then LGTM. Thanks for the contribution and my apologies for breaking you!

**Review by dconeybe — APPROVED** [review]

File: packages/util/src/environment.ts [hunk 2]
```diff
@@ -138,6 +138,7 @@ export function isNodeSdk(): boolean {
 export function isSafari(): boolean {
   return (
     !isNode() &&
+    navigator.userAgent !== undefined &&
```
Comment (dconeybe) [inline packages/util/src/environment.ts:141]: My apologies... could you replace `navigator.userAgent !== undefined` with simply `navigator.userAgent`? That style is more conventional in our code base. Thanks!

**Review by dconeybe — CHANGES_REQUESTED** [review]

**Review by DellaBitta — APPROVED** [review]

**Review by dconeybe — APPROVED** [review]

**Comment by dconeybe** [comment]
Looks like GitHub Actions fails miserably when run in a PR from an external contributor. I've opened https://github.com/firebase/firebase-js-sdk/pull/7965 to run them under my name. We can use those results to gate this PR's merge then just force-merge this one.
