### PR TITLE
Export StorageError class instead of interface

### LINKED ISSUE #6944: Export StorageError
### [REQUIRED] Describe your environment

  * Operating System version: NA
  * Browser version: NA
  * Firebase SDK version: 0.10.0
  * Firebase Product: storage

### [REQUIRED] Describe the problem

I noticed when a file doesn't exit in a Firestore collection, it throws an instance of `StorageError` class, it used to be `FirebaseError`. Now the problem is `StorageError` is not exported in `storage-public.d.ts` (only its interface is exported) so I cannot check the catches error with

```typescript
error instanceof StorageError
```

#### Steps to reproduce:

Try to import `StorageError` class, the interface is importable, but we need to import the class.

#### Relevant Code:

```typescript
import { StorageError } from '@firebase/storage';

console.log(null instance StorageError);
```

### PR DESCRIPTION
**Pull request by maneesht**
Fixes #6944

### CODE REVIEW

**Comment by tonyjhuang** [comment]
I'm generally okay with this, is this consistent with other Firebase sdks?

**Comment by maneesht** [comment]
> I'm generally okay with this, is this consistent with other Firebase sdks?

Yes. Every other SDK (except Auth) uses Classes instead of interfaces

**Review by tonyjhuang — APPROVED** [review]

**Review by tonyjhuang — APPROVED** [review]
thanks for the changes, please have someone from the core js team to approve too before submitting

File: packages/storage/src/public-types.ts [hunk 1]
```diff
@@ -17,13 +17,10 @@
...
 import { FirebaseApp, _FirebaseService } from '@firebase/app';
-import {
-  CompleteFn,
-  FirebaseError,
-  NextFn,
-  Subscribe,
-  Unsubscribe
-} from '@firebase/util';
+import { CompleteFn, NextFn, Subscribe, Unsubscribe } from '@firebase/util';
+import { StorageError } from './implementation/error';
```
Comment (hsubox76) [inline packages/storage/src/public-types.ts:21]: Is the import used in this file?

File: packages/storage/src/public-types.ts [hunk 2]
```diff
@@ -17,13 +17,10 @@
...
+
+export { StorageError, StorageErrorCode } from './implementation/error';
```
Comment (hsubox76) [inline packages/storage/src/public-types.ts:23]: I think this should be exported directly from `src/api.ts`. I think we had some weird bugs before when non-types were exported from a file that otherwise only exported types, but even if that's not a problem, just for organizational purposes.

**Review by hsubox76 — COMMENTED** [review]
I actually just realized I think we originally did this to make the type export neater and hide unnecessary stuff like the private members and the getters and setters but I guess there is no way around it if users want to use `instanceof`.

File: packages/storage/src/public-types.ts (hunk 1 above)
Comment (maneesht) [reply packages/storage/src/public-types.ts:21]: Yes, we reference it throughout

File: common/api-review/storage.api.md [hunk 3]
```diff
@@ -217,8 +215,71 @@ export interface SettableMetadata {
...
+    };
+    get serverResponse(): null | string;
+    set serverResponse(serverResponse: string | null);
+    // (undocumented)
+    get status(): number;
+    set status(status: number);
+    }
+
+// @public
+export const enum StorageErrorCode {
```
Comment (hsubox76) [inline common/api-review/storage.api.md:232]: Sorry, wasn't paying attention earlier to a new enum being exported as well, I think there are some problems with exporting a `const enum` (for a certain set of users) so I think this needs to be changed to just `enum` here https://github.com/firebase/firebase-js-sdk/blob/68369740aa8802ea8391432f10f9baa4abb84aa0/packages/storage/src/implementation/error.ts#L88
Background on const enum issues https://ncjamieson.com/dont-export-const-enums/

**Review by hsubox76 — APPROVED** [review]

File: packages/storage-types/index.d.ts [hunk 4]
```diff
@@ -16,10 +16,10 @@
  */
 
 import { FirebaseApp } from '@firebase/app-types';
+import { StorageError as FirebaseStorageError } from '@firebase/storage';
```
Comment (hsubox76) [inline packages/storage-types/index.d.ts:19]: I'm not sure if this will work, as (1) `@firebase/storage` isn't a dependency of `@firebase/storage-types` so it's not great to import from it. In practice it should always be there because users install all of Firebase at once, but it doesn't seem right and I think some of the newer package managers yell about this. (2) I think this is sort of exporting a class from a `d.ts` file which I don't think you can do, not 100% sure, maybe it just treats it as a type. I know we were importing FirebaseError before which is a class but it was only used as an `extends` for an interface, and that interface was what's exported. Hm, is there any way to make an interface from scratch here that matches the StorageError class?

File: .changeset/hungry-glasses-impress.md [hunk 5]
```diff
@@ -0,0 +1,6 @@
+---
+"firebase": minor
+"@firebase/storage": minor
```
Comment (hsubox76) [inline .changeset/hungry-glasses-impress.md:3]: Add `storage-types` and `storage-compat`
