### PR TITLE
Fire onInit callback if instance is already available

### LINKED ISSUE #4932: 8.6.2 breaks auth/firestore rules
### [REQUIRED] Describe your environment

  * Operating System version: Mac OS X
  * Browser version: Chrome
  * Firebase SDK version: 8.6.2
  * Firebase Product: auth

### [REQUIRED] Describe the problem

After upgrading from firebase 8.6.1 → 8.6.2, I get the "ERROR FirebaseError: Missing or insufficient permissions." error when trying to access protected docs/collections. Rolling back to 8.6.1 fixes the issue.

#### Steps to reproduce:

Upgrade from Firebase 8.6.1 → 8.6.2
My app is running on Angular 12

### PR DESCRIPTION
**Pull request by schmidt-sebastian**
This changes Firestore's initialization to detect Auth if Auth is available during client startup. Right now, we only detect once the `setTimeout` call fires.

Fixes https://github.com/firebase/firebase-js-sdk/issues/3218
Fixes https://github.com/firebase/firebase-js-sdk/issues/4953
Fixes #4932

### CODE REVIEW

File: packages/component/src/provider.ts [hunk 1]
```diff
@@ -263,9 +263,15 @@ export class Provider<T extends Name> {
    *
    * @returns a function to unregister the callback
    */
-  onInit(callback: OnInitCallBack<T>): () => void {
+  onInit(callback: OnInitCallBack<T>, identifier?: string): () => void {
```
Comment (Feiyang1) [inline packages/component/src/provider.ts:266]: Can you please add a comment for the argument `identifier`?

**Review by Feiyang1 — APPROVED** [review]

File: packages/component/src/provider.ts (hunk 1 above)
Comment (Feiyang1) [reply packages/component/src/provider.ts:266]: Should we trigger the callback for all instances that have already been created? That's what would happen if those were created after the onInit callback is registered. So that we have a consistent behavior no matter whether the callback is registered before or after initialization (it will be invoked for every instances created).

**Review by Feiyang1 — CHANGES_REQUESTED** [review]

File: packages/component/src/provider.ts (hunk 1 above)
Comment (schmidt-sebastian) [reply packages/component/src/provider.ts:267]: As discussed offline, I think the current behavior already achieves this. All callbacks that are registered for an existing component will be invoked once when registered (new logic). All callbacks that are registered before a component is available will be invoked once the component is available (existing logic). 

Let me know if there are any more questions.

Comment (Feiyang1) [reply packages/component/src/provider.ts:267]: Sorry I wasn't clear. What I meant is we don't need the `identifier` argument, and a callback can be invoked multiple times (once per identifier) when registered if the component support multiple instances and there are already multiple instances initialized.

File: packages/component/src/provider.ts [hunk 2]
```diff
@@ -261,11 +261,18 @@ export class Provider<T extends Name> {
...
    * The function is invoked SYNCHRONOUSLY, so it should not execute any longrunning tasks in order to not block the program.
    *
+   * @param identifier An optional instance identifier
    * @returns a function to unregister the callback
    */
-  onInit(callback: OnInitCallBack<T>): () => void {
+  onInit(callback: OnInitCallBack<T>, identifier?: string): () => void {
     this.onInitCallbacks.add(callback);
 
+    const instance = this.getImmediate({ identifier, optional: true });
```
Comment (Feiyang1) [inline packages/component/src/provider.ts:270]: Can you please add a comment that OnInit() is only intended to be used for `EXPLICIT` components, so getImmediate() will never initialize a new instance?

File: packages/component/src/provider.ts (hunk 1 above)
Comment (Feiyang1) [reply packages/component/src/provider.ts:267]: as per discussion offline, we will change the callback to be associated with an identifier.

File: packages/component/src/provider.ts [hunk 3]
```diff
@@ -261,13 +261,24 @@ export class Provider<T extends Name> {
...
    */
-  onInit(callback: OnInitCallBack<T>): () => void {
-    this.onInitCallbacks.add(callback);
+  onInit(callback: OnInitCallBack<T>, identifier?: string): () => void {
+    const normalizedIdentifier = this.normalizeInstanceIdentifier(identifier);
+    const existingInstances =
+      this.onInitCallbacks.get(normalizedIdentifier) ??
+      new Set<OnInitCallBack<T>>();
+    existingInstances.add(callback);
+    this.onInitCallbacks.set(normalizedIdentifier, existingInstances);
```
Comment (Feiyang1) [inline packages/component/src/provider.ts:273]:
```suggestion
    const existingCallbacks =
      this.onInitCallbacks.get(normalizedIdentifier) ??
      new Set<OnInitCallBack<T>>();
    existingCallbacks.add(callback);
    this.onInitCallbacks.set(normalizedIdentifier, existingCallbacks);
```

File: packages/component/src/provider.ts [hunk 4]
```diff
@@ -261,13 +261,24 @@ export class Provider<T extends Name> {
...
+
+    const existingInstance = this.instances.has(normalizedIdentifier);
+    if (existingInstance) {
+      callback(existingInstance, normalizedIdentifier);
+    }
 
     return () => {
-      this.onInitCallbacks.delete(callback);
+      this.onInitCallbacks.get(normalizedIdentifier)!.delete(callback);
```
Comment (Feiyang1) [inline packages/component/src/provider.ts:281]: How about 
```suggestion
      existingCallbacks.delete(callback);
```

File: packages/component/.run/All Tests.run.xml [hunk 5]
```diff
@@ -0,0 +1,19 @@
+<component name="ProjectRunConfigurationManager">
```
[the remark this answers is not in the document]
Comment (schmidt-sebastian) [reply packages/component/.run/All Tests.run.xml:1]: Okay - these are pretty helpful for me though :)

File: packages/component/src/provider.test.ts [hunk 6]
```diff
@@ -181,6 +181,46 @@ describe('Provider', () => {
       expect(callback2).to.have.been.calledOnce;
     });
 
+    it('invokes callback for existing component', () => {
```
[the remark this answers is not in the document]
Comment (schmidt-sebastian) [reply packages/component/src/provider.test.ts]: Done

File: packages/component/src/provider.ts (hunk 4 above)
Comment (schmidt-sebastian) [reply packages/component/src/provider.ts]: Uhm, clever :) Thanks.

**Review by Feiyang1 — APPROVED** [review]
pending CI.
