### PR TITLE
Check for process.env in isMockPersistence

### LINKED ISSUE #2404: Firestore enablePersistence(): “Error enabling offline persistence. Falling back to persistence disabled”
### Describe your environment

  * Operating System version: All tested (Win10, OSX El capitain)
  * Browser version: Latest Chrome 6 Firefox
  * Firebase SDK version: 7.5.0
  * Firebase Product: Firestore

### Describe the problem
I'm making a PWA app with Ionic 4 (angular) and Firebase Cloud Firestore as database. And it was working fine until just now when i wanted to enable offline persistance. Using AngularFire and the docs is not hard to follow. This is is how i enable it in my app-module.ts
```typescript
@NgModule({
  declarations: [AppComponent],
  entryComponents: [],
  imports: [
    BrowserModule,
    IonicModule.forRoot(),
    AppRoutingModule,
    ComponentsModule,
    AngularFireModule.initializeApp(environment.firebaseConfig),
    AngularFirestoreModule.enablePersistence(), // <- Trying to enable here
    AngularFireAuthModule,
  ServiceWorkerModule.register('ngsw-worker.js', { enabled: environment.production })
  ],
  providers: [
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
    GlobalService
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}
```
When i run the app i get this warning in Chrome Developer Tools:
> Error enabling offline persistence. Falling back to persistence disabled: TypeError: Cannot read property 'USE_MOCK_PERSISTENCE' of undefined

and a similar one in Firefox:
> Error enabling offline persistence. Falling back to persistence disabled: TypeError: process.env is undefined

#### Steps to reproduce:
enable it in app.module.ts with:
> AngularFirestoreModule.enablePersistence()

#### Relevant Code:

You can se the error live @ https://cubetrainer.nu

### PR DESCRIPTION
**Pull request by thebrianchen**
Fixes #2404. 

In this particular instance, the user's `process` variable was defined, but `process.env` was not defined, which triggered an error when checking for `process.env.USE_MOCK_PERSISTENCE`.

### CODE REVIEW

File: packages/firestore/src/local/simple_db.ts [hunk 1]
```diff
@@ -209,6 +209,7 @@ export class SimpleDb {
   static isMockPersistence(): boolean {
     return (
       typeof process !== 'undefined' &&
+      typeof process.env !== 'undefined' &&
       process.env.USE_MOCK_PERSISTENCE === 'YES'
```
Comment (schmidt-sebastian) [inline packages/firestore/src/local/simple_db.ts]: Does `process?.env?. USE_MOCK_PERSISTENCE === YES` work (you might want to look at the generated code)?

Comment (thebrianchen) [reply packages/firestore/src/local/simple_db.ts]: ah yes, the newest TS tech!
