### PR TITLE
Wait for service worker registration to become active before any operations

### LINKED ISSUE #7693: getToken throw error :  DOMException: Failed to execute 'subscribe' on 'PushManager': Subscription failed - no active Service Worker
### Operating System

win 10

### Browser Version

chrome 118.0.5993.71 (Official Build) (64-bit)

### Firebase SDK Version

10.4.0

### Firebase SDK Product:

Messaging

### Describe your project's tooling

https://www.gstatic.com/firebasejs/10.4.0/firebase-app-compat.js
https://www.gstatic.com/firebasejs/10.4.0/firebase-messaging-compat.js

### Describe the problem

1. clear cookie
image

2. when open my web site for the first time, getToken throw the following error【NG】
image

4. when open my web site for the second time or refresh the tab, getToken works fine.
image
 

### Steps and code to reproduce issue

```
return this.messaging.getToken({
            vapidKey : this.vapidKey,
        }).then((currentToken) => {
            if (currentToken) {
                console.log(currentToken);
                return currentToken;
            } else {
                console.log('No Instance ID token available. Request permission to generate one.');
                return null;
            }
        }).catch((err) => {
            console.error(err);
        });
```

### LINKED ISSUE #7784: Failed to execute 'subscribe' on 'PushManager': Subscription failed - no active Service Worker
### Operating System

Windows 10

### Browser Version

Chrome Version 96.0.4664.55 

### Firebase SDK Version

9.5.0

### Firebase SDK Product:

Messaging

### Describe your project's tooling

JS (via webpack deployment)
Generic HTML (and/or Typo3 CMS) with PHP technology

### Describe the problem

This is actually a follow-on and solution to these two closed bug reports, as no official solution was provided:

https://github.com/firebase/firebase-js-sdk/issues/6013
https://github.com/firebase/firebase-js-sdk/issues/5797

Cited information:
" Sometimes calling messaging getToken returns the error: Failed to execute 'subscribe' on 'PushManager': Subscription failed - no active Service Worker. It seems to only occur on the first page load, when the user refreshes the notifications work and there's no error anymore. "...

Please note I run the same code on two websites, swapping out the various keys required for each Firebase setup.
The websites are exact copies of each other,  running as entirely separate websites.
On website there is no problem at all. On the second website I see the getToken error mentioned above.

After further testing I can confirm this issue is related to some issue picking up the "default" service worker if not explicitly  referenced and registered.

`getToken(messaging, { vapidKey: 'XXXXXX' }`

As stated we don't have to send the serviceWorkerRegistration if it's using the default name. BUT sometimes (and there is no indication of why or when), the above request will return the error message without it. Perhaps it occurs when this initialisation code runs before the service worker has loaded in to memory? Or not. 
Regardless, the solution (and I would like confirmation that this is the defacto solution) is to register and include the service worker before making this request, even if you are using the default service worker filename "firebase-messaging-sw.js".

`const swRegistration = await navigator.serviceWorker.register('/firebase-messaging-sw.js');`
`getToken(messaging, { vapidKey:  'XXXXXX', serviceWorkerRegistration: swRegistration })`

If this is the solution, perhaps it would be better to make the serviceWorkerRegistration field mandatory rather than optional?

### Steps and code to reproduce issue

Steps to reproduce:
Add firebase-messaging-sw.js to root of domain
Call firebase initializeApp
Call firebase getMessaging
Ask and approve browser notification permission
Add firebase onMessage listener
Call firebaseawait getToken(messaging, {  vapidKey: <VAPID_KEY>  })
Error sometimes appears with Failed to execute 'subscribe' on 'PushManager': Subscription failed - no active Service Worker

Relevant Code:
firebase-messaging-sw.js is at the root of project and firebase gets initialised right away:

### PR DESCRIPTION
**Pull request by hsubox76**
[Examples on MDN](https://developer.mozilla.org/en-US/docs/Web/API/PushManager) seem to claim that `serviceWorkerRegistration.pushManager.subscribe()` can be called right after `await`ing `navigator.serviceWorker.register`, but that doesn't actually seem to be the case in practice. See issues https://github.com/firebase/firebase-js-sdk/issues/7784 and #7693.

When the user calls `getToken()` (and is using the default service worker), we await `register()` in `registerDefaultSw()` and we go ahead and call `pushManager.subscribe()` soon after. Unfortunately it's often not actually ready. Not sure if this is a bug - spec seems to indicate it should be ready?

One option is to await `navigator.serviceWorker.ready` but this can be tricky depending on the scope of the service worker, where it may not consider your service worker the page's default service worker. It seems to hang in my test apps. It also may get mixed up with other service workers from other apps on the same page.

Instead, we can listen for events on the specific service worker we just registered and check when the `state` becomes "active". Borrowed some working code for this from various contributors in https://github.com/firebase/firebase-js-sdk/issues/7693#issuecomment-2408692016 (Thank you!)

Fixes #7784
Fixes #7693

### CODE REVIEW

**Review by zwu52 — APPROVED** [review]
lgtm. thanks for the change!

File: packages/messaging/src/helpers/registerDefaultSw.ts [hunk 1]
```diff
@@ -39,9 +39,40 @@ export async function registerDefaultSw(
...
+    if (registration.active) {
+      resolve();
+    }
+    const incomingSw = registration.installing || registration.waiting;
+    if (incomingSw) {
+      incomingSw.onstatechange = ev => {
+        if ((ev.target as ServiceWorker)?.state === 'activated') {
+          incomingSw.onstatechange = null;
+          resolve();
+        }
```
Comment (dlarocque) [inline packages/messaging/src/helpers/registerDefaultSw.ts:72]: What happens here if the service worker was installing but ran into an error (could be a JS error) and doesn't transition to the activated state?

I'm generally worried that the state may never become active, causing this to never resolve or reject. What do you think about adding a timeout to reject after some time?

Comment (hsubox76) [reply packages/messaging/src/helpers/registerDefaultSw.ts]: I added a 10s timeout. I originally set it up to be customizable in case people had very slow devices or something but it involved so many changes (getToken and deleteToken both need a new param) I didn't think it was a good idea for an edge case. In my testing, I had to set the timeout all the way down to 1ms in order for it to be triggered so the registration should be pretty fast?

File: packages/messaging/src/helpers/registerDefaultSw.ts [hunk 2]
```diff
@@ -39,9 +39,40 @@ export async function registerDefaultSw(
...
+      };
+    } else {
+      reject(new Error('No incoming service worker found.'));
+    }
```
[the remark this answers is not in the document]
Comment (hsubox76) [reply packages/messaging/src/helpers/registerDefaultSw.ts]: I changed it to an if/else but not sure if this affects the timing at all.

**Review by dlarocque — APPROVED** [review]

File: packages/messaging/src/helpers/registerDefaultSw.ts (hunk 1 above)
Comment (dlarocque) [reply packages/messaging/src/helpers/registerDefaultSw.ts]: Sounds good!

File: packages/messaging/src/helpers/registerDefaultSw.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (dlarocque) [reply packages/messaging/src/helpers/registerDefaultSw.ts]: Yeah this is a tricky timing issue. I think now the SW could become active before we add the event listener, causing us to miss the `activated` event. For example:
1. registration is waiting
2. registration is not yet active, so we don't resolve immediately on line 79.
3. registration becomes active, and the `'activated'` event fires
4. attach registration state event listener
5. event listener never fires because we missed the `'activated'` event and we reject the promise after 10s

This is just me speculating, I'm not sure if this order of events is possible.
