### PR TITLE
Fixed issue where we call connectDatabaseToEmulator twice

### LINKED ISSUE #6853: Database tries to call connectDatabaseEmulator when already initialized, leading to FIREBASE FATAL ERROR
### [REQUIRED] Describe your environment

  * Operating System version: MacOS Monterrey 12.6
  * Browser version: Google Chrome 108.0.5359.94
  * Firebase SDK version: 9.14.0
  * Firebase Product: database

#### Steps to reproduce:

I'm using the nextjs integration with firebase database and when there is a hot reload (ex. saving a file), the following error appears: Error: FIREBASE FATAL ERROR: Cannot call useEmulator() after instance has already been initialized. 
From the line:
```javascript
 export const database = getDatabase(firebaseApp);
```
When there has been no hot reload, everything works fine.

After more investigation I found that the code that connects the emulator differs from the one that connects the firebase emulator

```javascript
//firebase-js-sdk/packages/firestore/src/api/database.ts
export function getFirestore(
  appOrDatabaseId?: FirebaseApp | string,
  optionalDatabaseId?: string
): Firestore {
  const app: FirebaseApp =
    typeof appOrDatabaseId === 'object' ? appOrDatabaseId : getApp();
  const databaseId =
    typeof appOrDatabaseId === 'string'
      ? appOrDatabaseId
      : optionalDatabaseId || DEFAULT_DATABASE_NAME;
  const db = _getProvider(app, 'firestore').getImmediate({
    identifier: databaseId
  }) as Firestore;
  if (!db._initialized) {
    const emulator = getDefaultEmulatorHostnameAndPort('firestore');
    if (emulator) {
      connectFirestoreEmulator(db, ...emulator);
    }
  }
  return db;
}
```

```javascript
//firebase-js-sdk/packages/database/src/api/Database.ts
export function getDatabase(
  app: FirebaseApp = getApp(),
  url?: string
): Database {
  const db = _getProvider(app, 'database').getImmediate({
    identifier: url
  }) as Database;
  //In line 323 should be added if(!db._instanceStarted){
    const emulator = getDefaultEmulatorHostnameAndPort('database');
    if (emulator) {
      connectDatabaseEmulator(db, ...emulator);
    }
  //}
  return db;
}
//...
export function connectDatabaseEmulator(
  db: Database,
  host: string,
  port: number,
  options: {
    mockUserToken?: EmulatorMockTokenOptions | string;
  } = {}
): void {
  db = getModularInstance(db);
  db._checkNotDeleted('useEmulator');
  if (db._instanceStarted) {  //This check becomes redundant
    fatal(
      'Cannot call useEmulator() after instance has already been initialized.'
    );
  }
  //...
}
```

I believe that those changes would fix the issue.

#### My package.json dependencies
```json
"dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.2.0",
    "@fortawesome/free-brands-svg-icons": "^6.2.0",
    "@fortawesome/free-solid-svg-icons": "^6.2.0",
    "@fortawesome/react-fontawesome": "^0.2.0",
    "bootstrap": "4.6.2",
    "firebase": "^9.14.0",
    "firebaseui": "^6.0.1",
    "jquery": "^3.6.1",
    "next": "^13.0.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "sass": "^1.55.0"
}
```

### PR DESCRIPTION
**Pull request by maneesht**
Fixes #6853

### CODE REVIEW

**Review by jamesdaniels — APPROVED** [review]
LGTM

File: packages/database/src/api/Database.ts [hunk 1]
```diff
@@ -320,9 +320,11 @@ export function getDatabase(
...
-  if (emulator) {
-    connectDatabaseEmulator(db, ...emulator);
+  if (!db._instanceStarted) {
+    const emulator = getDefaultEmulatorHostnameAndPort('database');
+    if (emulator) {
+      connectDatabaseEmulator(db, ...emulator);
+    }
   }
   return db;
 }
```
Comment (IanWyszynski) [inline packages/database/src/api/Database.ts:330]: So, per the issue, can we remove the `if (db._instanceStarted)` on L353 in `connectDatabaseEmulator` now?

Comment (maneesht) [reply packages/database/src/api/Database.ts:330]: `connectDatabaseEmulator` is still a public function, so the user could still call it outside of the normal flow

**Review by IanWyszynski — APPROVED** [review]

**Review by hsubox76 — APPROVED** [review]
