### PR TITLE
[auth] Retry IndexedDB errors a fixed number of times

### LINKED ISSUE #1926: auth: Failed to execute 'transaction' on 'IDBDatabase'
### [REQUIRED] Describe your environment

  * Operating System version: Android/Windows
  * Browser version: Chrome
  * Firebase SDK version: 6.2.2
  * Firebase Product: auth

### [REQUIRED] Describe the problem

Migrating this issue on behalf of @alexplumb from #1533. We've seen this indexdb issue in Firestore on Safari 12.2 (both in #1533 and the canonical one for that issue, #1670). 

However, Alex doesn't seem to have persistence enabled, so firestore shouldn't even be looking at indexdb. The name of the indexdb in question is "firebaseLocalStorageDb" which looks like it's the auth db (https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/storage/indexeddb.js#L191)

#### Steps to reproduce:
Happens inconsistently; unable to reproduce. :(

### PR DESCRIPTION
**Pull request by avolkovi**
There appears to be an issue with webkit where it periodically closes the connections such as when the tab is backgrounded (https://bugs.webkit.org/show_bug.cgi?id=197050).  We can't repro, but Firestore did something similar and have stopped getting error reports.

Closes #1926

### CODE REVIEW

File: packages/auth/src/storage/indexeddb.js [hunk 1]
```diff
@@ -416,43 +455,42 @@ fireauth.storage.IndexedDB.prototype.onIDBRequest_ =
...
-        var objectStore = self.getDataObjectStore_(
-            self.getTransaction_(dbTemp, true));
-        return self.onIDBRequest_(objectStore.get(key));
-      })
-      .then(function(data) {
-        var objectStore = self.getDataObjectStore_(
-            self.getTransaction_(dbTemp, true));
+  let isLocked = false;
+  return this
+    .withRetry_((db) => {
```
Comment (Feiyang1) [inline packages/auth/src/storage/indexeddb.js:460]: Does closure compile it to regular functions? I wasn't sure if you can use arrow functions in closure.

**Review by Feiyang1 — APPROVED** [review]

File: packages/auth/src/storage/indexeddb.js (hunk 1 above)
Comment (avolkovi) [reply packages/auth/src/storage/indexeddb.js:460]: seems to compile to `function() {}.bind(this)` https://github.com/google/closure-compiler/issues/2853

**Review by trevorhere — COMMENTED** [review]
looks good to me!
